export const SAVE_DISH_REQUEST = "SAVE_DISH_REQUEST";
export const FETCH_DISH_REQUEST = "FETCH_DISH_REQUEST";
export const UPDATE_DISH_REQUEST = "UPDATE_DISH_REQUEST";
export const DELETE_DISH_REQUEST = "DELETE_DISH_REQUEST";
export const DISH_SUCCESS = "DISH_SUCCESS";
export const DISH_FAILURE = "DISH_FAILURE";
