export const SAVE_ORDER_REQUEST = "SAVE_ORDER_REQUEST";
export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";
